---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: eslint-2
    config:
      config: ".eslintrc.js"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.json"
  - "**.md"
exclude_paths:
- test/
- lib/
- node_modules/
