---
plugins:
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.json"
  - "**.md"
exclude_paths:
- test/
- dist/
- node_modules/
